### PR TITLE
normalize whitespace in log messages outputting user-provided parameters

### LINKED ISSUE #388: Insufficient scrubbing of user input values prior to logging
### Checked for duplicates

Yes - I've already checked

### 🐛 Describe the bug

See https://github.com/NASA-PDS/registry-api/security for possible vulnerabilities:
- https://github.com/NASA-PDS/registry-api/security/code-scanning/59
- https://github.com/NASA-PDS/registry-api/security/code-scanning/58
- https://github.com/NASA-PDS/registry-api/security/code-scanning/57
- https://github.com/NASA-PDS/registry-api/security/code-scanning/56
- https://github.com/NASA-PDS/registry-api/security/code-scanning/55
- https://github.com/NASA-PDS/registry-api/security/code-scanning/54
- https://github.com/NASA-PDS/registry-api/security/code-scanning/53

### 🕵️ Expected behavior

I expected the user inputs would be scrubbed prior to logging

### 📜 To Reproduce

See code scans

### 🖥 Environment Info

N/A

### 📚 Version of Software Used

Latest as of 11/17/2023

### 🩺 Test Data / Additional context

_No response_

### 🦄 Related requirements

_No response_

### ⚙️ Engineering Details

_No response_

### PR DESCRIPTION
**Pull request by alexdunnjpl**
## 🗒️ Summary
Applies `StringUtils.normalizeSpace()` to user-provided values when echoed to log output, to address CRLF injection concerns.

There's probably a way of configuring the logger to perform this automatically, but we're running quick and dirty today, lads.

## ⚙️ Test Data and/or Report
n/a

## ♻️ Related Issues
Fixes #388

### CODE REVIEW

File: service/src/main/java/gov/nasa/pds/api/registry/controller/SwaggerJavaTransmuter.java [hunk 1]
```diff
@@ -78,11 +79,11 @@ protected ResponseEntity<Object> processs(EndpointHandler handler, URIParameters
       return new ResponseEntity<Object>(this.errorMessageFactory.get(e),
           HttpStatus.INTERNAL_SERVER_ERROR);
     } catch (LidVidMismatchException e) {
-      log.warn("The lid(vid) '" + parameters.getIdentifier()
-          + "' in the data base type does not match given type '" + parameters.getGroup() + "'");
+      log.warn("The lid(vid) (whitespace-normalized) '" + StringUtils.normalizeSpace(parameters.getIdentifier().toString())
+          + "' in the data base type does not match given type () '" + StringUtils.normalizeSpace(parameters.getGroup()) + "'");
```
Comment (tloubrieu-jpl) [inline service/src/main/java/gov/nasa/pds/api/registry/controller/SwaggerJavaTransmuter.java]: why do we have the parenthesis with empty content `()` in the message ?

**Review by tloubrieu-jpl — APPROVED** [review]
A minor change requested if this is the answer to my comment of the code.

File: service/src/main/java/gov/nasa/pds/api/registry/controller/SwaggerJavaTransmuter.java (hunk 1 above)
Comment (alexdunnjpl) [reply service/src/main/java/gov/nasa/pds/api/registry/controller/SwaggerJavaTransmuter.java]: No idea - fixed.  Thanks for the catch
