### PR TITLE
issue 260: add parsing exception handling

### LINKED ISSUE #206: When q="" the returned status is 500 instead of 400
## 🐛 Describe the bug

See for example request:
curl --request GET 'http://localhost:8080/collections?q=""'

## 🕵️ Expected behavior

The status should be 400, bad request

## 📚 Version of Software Used

Latest development version, 1.2.0-SNAPSHOT

### LINKED ISSUE #252: Invalid LidvidsContext bounds fails internally and returns http500, vs expected handle and http400
## 💡 Description
ex.
http://localhost:8080/collections/urn:nasa:pds:mars2020_supercam:data_calibrated_audio::4.0/products?start=0&limit=-1
http://localhost:8080/collections/urn:nasa:pds:mars2020_supercam:data_calibrated_audio::4.0/products?start=-1&limit=1
http://localhost:8080/collections/urn:nasa:pds:mars2020_supercam:data_calibrated_audio::4.0/products?start=-1&limit=-1

All three should throw during `URIParameters` instantiation, with exceptions being caught and handled.

### LINKED ISSUE #255: Incorporate misc changes loosely-related to #252
## 💡 Description
Preliminary work undertaken as part of #252 which does not actually resolve it (since it has been deprioritized but the work is still useful).
 - Add internal `IllegalArgumentException` to invalid `start` and `limit` setter calls
 - Remove summaryOnly-related internal code and rework Singular/Plural API route behaviour to be more explicit

### LINKED ISSUE #260: api does not return 400 error when q parameter value cannot be parsed
### Checked for duplicates

Yes - I've already checked

### 🐛 Describe the bug

When I do request:

curl --request GET 'http://localhost:8081//classes/collections?q=""'

I get a 500 error.

### 🕵️ Expected behavior

I expected a 400 error with an explicit message saying the query string q is invalid and cannot be parsed.

### 📜 To Reproduce

See integration tests in repository 'registry'

### 🖥 Environment Info

_No response_

### 📚 Version of Software Used

1.2.0-SNAPSHOT

### 🩺 Test Data / Additional context

_No response_

### 🦄 Related requirements

🦄 #xyz

### ⚙️ Engineering Details

I suugest to work on this ticket together with:
https://github.com/NASA-PDS/registry-api/issues/252
https://github.com/NASA-PDS/registry-api/issues/241 (mostly duplicate)

This requires to reintroduce invalid{Parameter}Exception

They will be catched and throw an InvalidRequestException in the processs transmutter method.

I suggest to create a super class of exception PDSAPIException to handle all the known exceptions. This will avoid to repeat all the thrown exception in the ranmute/rhandler/efLogic... methods, e.g. https://github.com/NASA-PDS/registry-api/blob/d1d0172f6147c33d6c598ceaf7052f19d63ed873/service/src/main/java/gov/nasa/pds/api/registry/controller/Member.java#L30

There was also some discussion started on that in ticket https://github.com/NASA-PDS/registry-api/issues/252

I think that would be useful to have a super type of exception,

### PR DESCRIPTION
**Pull request by al-niessner**
## 🗒️ Summary
Another simple one line change to add more exception handling back to HTTP error codes and messaging.

## ⚙️ Test Data and/or Report
```
$ curl --request GET 'http://localhost:8080//classes/collections?q=%22%22'
{"request":"//classes/collections","message":"The given search string '""' cannot be parsed."}
```

**HOWEVER**

```
$ curl --request GET 'http://localhost:8080//classes/collections?q=""'
<!doctype html><html lang="en"><head><title>HTTP Status 400 – Bad Request</title><style type="text/css">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 400 – Bad Request</h1></body></html>n
```

**BECAUSE** the error is prior to registry-api in the apache code as the log shows which is a completely different problem:

```
java.lang.IllegalArgumentException: Invalid character found in the request target [//classes/collections?q="" ]. The valid characters are defined in RFC 7230 and RFC 3986
	at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:494) ~[tomcat-embed-core-9.0.63.jar:9.0.63]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:271) ~[tomcat-embed-core-9.0.63.jar:9.0.63]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) ~[tomcat-embed-core-9.0.63.jar:9.0.63]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:890) ~[tomcat-embed-core-9.0.63.jar:9.0.63]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1743) ~[tomcat-embed-core-9.0.63.jar:9.0.63]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[tomcat-embed-core-9.0.63.jar:9.0.63]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) ~[tomcat-embed-core-9.0.63.jar:9.0.63]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) ~[tomcat-embed-core-9.0.63.jar:9.0.63]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-9.0.63.jar:9.0.63]
	at java.base/java.lang.Thread.run(Thread.java:829) ~[na:na]
```

## ♻️ Related Issues
closes #260 
closes #255 
closes #252
closes #206

### CODE REVIEW

**Comment by al-niessner** [comment]
@alexdunnjpl @jordanpadams @nutjob4life @tloubrieu-jpl 

This is how you solve exception problems. The whole point of reordering the code was to make a single place where exceptions are handled and turned back into http errors. It should become distributed again and certainly not while UserParameters are being instantiated.

The better flow and one that currently exists is that you take what is as is and load it into a Java object for simpler processing. Once you have the object and the connection context from spring-something, then you have all the bits you need to start error processing. If you try to do it too early, then you have 10000 different blocks all doing exactly the same exception handling - okay, 4 or so blocks without using hyperbole. The way the code is currently structured, all endpoints have the same error handling because there is this one and only one block that handles exceptions. Not sure why that is so terrible or hard. The advantage is that no more cut-n-paste of code which is the quintessential [anti-pattern](https://sourcemaking.com/antipatterns/cut-and-paste-programming).

So, I see lots of questioning on breaking this all apart and making it more confusing with even more nested exceptions when simply adding to JavaSwaggerTransmutter.process() all that needs to be done because no exception can be thrown outside of that method and that method does all of the exception handling. Miraculous on stop shop.

Ready for review.

**Comment by alexdunnjpl** [comment]
@al-niessner is there some context from in-person discussion I've missed, or is this all regarding the in-issue discussion in #252?

I'm having some trouble parsing your comment if it's the latter - is the assertion that 

> Add internal IllegalArgumentException to invalid start and limit setter calls

is a bad approach, or is there some relation to 

> Remove summaryOnly-related internal code and rework Singular/Plural API route behaviour to be more explicit

?  My fault for opening a PR with two unrelated changes I suppose lol.

_EDIT_ Oh nevermind - I see the engineering details in #260 which I presume is what you're talking about.  Let me know if there's anything in #256 I need to rethink.

File: service/src/main/java/gov/nasa/pds/api/registry/controller/SwaggerJavaTransmuter.java [hunk 1]
```diff
@@ -114,6 +116,10 @@ protected ResponseEntity<Object> processs(EndpointHandler handler, URIParameters
     } catch (NothingFoundException e) {
       log.warn("Could not find any matching reference(s) in database.");
       return new ResponseEntity<Object>(ErrorFactory.build(e, this.request), HttpStatus.NOT_FOUND);
+    } catch (NoViableAltException | ParseCancellationException e) {
+      log.warn("The given search string '" + parameters.getQuery() + "' cannot be parsed.");
```
Comment (alexdunnjpl) [inline service/src/main/java/gov/nasa/pds/api/registry/controller/SwaggerJavaTransmuter.java:120]: Maybe log.info is more appropriate here, given that it's just bad user input?

**Review by alexdunnjpl — APPROVED** [review]
LGTM

**Review by tloubrieu-jpl — APPROVED** [review]
Yes, that is much simpler that what I proposed indeed, thanks Al

**Comment by tloubrieu-jpl** [comment]
@al-niessner @alexdunnjpl I m just realizing that fix does not help yet to fix the ticket https://github.com/NASA-PDS/registry-api/issues/252 but we'll cross that bridge when we will be there.

**Comment by al-niessner** [comment]
@alexdunnjpl @tloubrieu-jpl 

Agreed. I opened #252 again with an explanation.
